Use env var "OSM_PUMPS_QUERY"

diff --git a/.github/workflows/pumps-dev.yml b/.github/workflows/pumps-dev.yml
--- a/.github/workflows/pumps-dev.yml
+++ b/.github/workflows/pumps-dev.yml
@@ -5,10 +5,6 @@ on:
 #  repository_dispatch:
 #    types: [pumps_cron]
 
-env:
-  # Query Magdeburg trees
-  QUERY: '[out:json][bbox:52.0124,11.4100, 52.2497,11.8330];(node["man_made"="water_well"];);out;>;out;'
-
 jobs:
   pumps:
     environment: development
@@ -19,9 +15,37 @@ jobs:
         uses: actions/checkout@v3
       - name: build the harvester
         run: cd pumps-harvester && docker build --tag "${GITHUB_REPOSITORY}:${GITHUB_REF##*/}" .
-      - name: output query
-        run: echo "$QUERY"
       - name: run the harvester
-        run: docker run -v /tmp:/tmp "${GITHUB_REPOSITORY}:${GITHUB_REF##*/}" /tmp/out.json -q "$QUERY"
-      - name: File output
-        run: cat /tmp/out.json
+        run: docker run -v /tmp:/tmp "${GITHUB_REPOSITORY}:${GITHUB_REF##*/}" /tmp/out.json -q "{{ vars.OSM_PUMPS_QUERY }}"
+      - name: Upload file to supabase
+        run: |
+          getStatusCode=$(curl -s -o /dev/null -w "%{http_code}" \
+            -X GET \
+            ${{ vars.SUPABASE_URL }}/storage/v1/object/info/public/${{ vars.SUPABASE_DATA_ASSETS_BUCKET }}/pumps.geojson)
+          if [ "$getStatusCode" = "200" ]; then
+            putStatusCode=$(curl -s -o /dev/null -w "%{http_code}" \
+              -X PUT \
+              -H "Authorization: Bearer ${{ secrets.SUPABASE_ACCESS_TOKEN }}" \
+              -H "Content-Type: application/geo+json" \
+              -d "@${{ steps.pumps.outputs.file }}" \
+              ${{ vars.SUPABASE_URL }}/storage/v1/object/${{ vars.SUPABASE_DATA_ASSETS_BUCKET }}/pumps.geojson)
+            if [ "$putStatusCode" = "200" ]; then
+              echo "Uploading to Supabase successful"
+            else
+              echo "Uploading to Supabase failed"
+              exit 1
+            fi
+          else
+            postStatusCode=$(curl -s -o /dev/null -w "%{http_code}" \
+              -X POST \
+              -H "Authorization: Bearer ${{ secrets.SUPABASE_ACCESS_TOKEN }}" \
+              -H "Content-Type: application/geo+json" \
+              -d "@${{ steps.pumps.outputs.file }}" \
+              ${{ vars.SUPABASE_URL }}/storage/v1/object/${{ vars.SUPABASE_DATA_ASSETS_BUCKET }}/pumps.geojson)
+            if [ "$postStatusCode" = "200" ]; then
+              echo "Uploading to Supabase successful"
+            else
+              echo "Uploading to Supabase failed"
+              exit 1
+            fi
+          fi         
